@startuml
'https://plantuml.com/sequence-diagram

autonumber 1.1

协调者 -> 参与者集群:询问各参与者可以正常执行事务
参与者集群 -> 参与者集群:执行事务但不提交
参与者集群 -> 协调者:所有参与者都可以执行事务

autonumber 2.1
协调者-> 参与者集群:向各参与者发起事务提交通知
参与者集群 -> 参与者集群:提交事务，并释放锁资源
参与者集群 -> 协调者:反馈结果
@enduml

@startuml
'https://plantuml.com/sequence-diagram

autonumber 1.1

协调者 -> 参与者集群:询问各参与者可以正常执行事务
参与者集群 -> 参与者集群:执行事务但不提交
参与者集群 -> 协调者:一个或多个参与者未成功执行事务，或在约定时间内未返回结果

autonumber 2.1
协调者-> 参与者集群:向各参与者发起事务回滚通知
参与者集群 -> 参与者集群:回滚事务，并释放锁资源
参与者集群 -> 协调者:反馈结果
@enduml